ALTER TABLE viajes ADD COLUMN IF NOT EXISTS driver_depto TEXT DEFAULT '';
ALTER TABLE viajes ADD COLUMN IF NOT EXISTS driver_phone TEXT DEFAULT '';
ALTER TABLE viajes ADD COLUMN IF NOT EXISTS total_km_inside DOUBLE PRECISION DEFAULT 0;
ALTER TABLE viajes ADD COLUMN IF NOT EXISTS total_km_outside DOUBLE PRECISION DEFAULT 0;
